---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart raspi-signage
  ansible.builtin.systemd:
    name: raspi-signage.service
    state: restarted
  when: not raspi_signage_use_lightdm
  become: true

- name: Restart lightdm
  ansible.builtin.systemd:
    name: lightdm
    state: restarted
  become: true

- name: Restart raspi-signage-virtual
  ansible.builtin.systemd:
    name: raspi-signage-virtual.service
    state: restarted
  become: true

- name: Restart raspi-signage-virtual-vnc
  ansible.builtin.systemd:
    name: raspi-signage-virtual-vnc.service
    state: restarted
  become: true
