<div id="property-exists-field">
    <div class="field">
        <?php echo $this->formLabel($elementPropertyId); ?>
        <div class="inputs">
            <?php echo $this->formElement($elementPropertyId); ?>
        </div>
    </div>
    <div class="field">
        <?php echo $this->formLabel($elementLabelExists); ?>
        <div class="inputs">
            <?php echo $this->formElement($elementLabelExists); ?>
        </div>
    </div>
    <div class="field">
        <?php echo $this->formLabel($elementLabelNotExists); ?>
        <div class="inputs">
            <?php echo $this->formElement($elementLabelNotExists); ?>
        </div>
    </div>
</div>
