---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart qdrant-backup.timer
  ansible.builtin.systemd:
    name: qdrant-backup.timer
    state: restarted
    enabled: true
  become: true
